### ISSUE TITLE
game launch error with P5D

### ISSUE THREAD

**Issue by MarioMasta64** [dots-tb/reF00D#1]
C1-6703-6 upon launch
ux0:tai/keys.bin exists
ur0:tai/config.txt contains ux0:tai/ref00d.skprx under kernel

whats wrong?

**Comment by TheRadziu** [comment]
keys have to be on `ur0:/tai/keys.bin` no matter where your tai config or f00d plugin is.

Not a bug, issue is invalid since its user error and should be closed.
