### ISSUE TITLE
Error C1-6703-6 on anything superior to 3.65

### ISSUE THREAD

**Issue by Fakkor** [dots-tb/reF00D#10]
I can't run anything higher than my CFW (3.65) that isn't already patched.

reF00D is not loaded, I'm certain of it.

For some reason, whatever plugin that's installed on ur0:/tai won't work, so I install them at ux0:/tai, and they work just fine then.

One thing that I noticed is that NoNpDRM was installed at ux0:/tai, so it doesn't appear listed at ur0:/tai/config.txt
I reinstalled NoNpDRM with Autoplugin to ur0 and accomodated the reF00D line below it

It still doesn't work. 
Any suggestion?

**Comment by CelesteBlue-dev** [comment]
taiHEN doesn't load plugins from ur0 when ux0:tai/config.txt exists. So remove it then reboot.

**Comment by CelesteBlue-dev** [comment]
No answer, no issue.
