### ISSUE TITLE
Require to enable unsafe homebrew?

### ISSUE THREAD

**Issue by theratz** [dots-tb/reF00D#13]
plugin doesn’t work when trying to lunch without enabling unsafe mode. it seems to work until you click start button in LiveArea Startup Screen. Then games start crashing (Secret of Mana completely crashed Stardew Valley Crashed back to LiveArea game startup screen). idk its just me or bug im on 3.60 henkaku 11 no enso

**Comment by CelesteBlue-dev** [comment]
of course you need unsafe mode

**Comment by theratz** [comment]
Thanks
