### ISSUE TITLE
Downgraded to 3.60, one game gives c1-6703-6, I use ref00d...

### ISSUE THREAD

**Issue by MessiahMozgus** [dots-tb/reF00D#14]
I understand that c1-6703-6 is an error that indicates a game requires firmware above the firmware you are running, but I have countless other games that are still working, following my downgrade from 3.65 to 3.60 using modoru. I use ref00d to bypass firmware requirements and its working fine on half a dozen recent games I've tried like Shakedown Hawaii.

The problem game is Helldivers with the final patch installed. It will run if I delete the patch folder for it. Oddly enough when I try checking for a new patch from the game's bubble screen, it doesnt detect any. I've tried refreshing live area and licenses from VitaShell. I've tried uninstalling the game and deleting its folders if found in app, appmeta, data, patch, repatch, then reinstalling from PKGj. I've tried downloading a comp pack in PKGj, but it says it needs a base pack before the one it can download but I dont see how to do that. Regardless, I shouldn't need comp packs right?

I also made a thread over here: https://www.reddit.com/r/VitaPiracy/comments/bzi9gf/downgraded_to_360_one_game_gives_c167036_i_use/

**Comment by Princess-of-Sleeping** [comment]
https://github.com/dots-tb/reF00D#troubleshooting

**Comment by MessiahMozgus** [comment]
> https://github.com/dots-tb/reF00D#troubleshooting

I'm aware. I always read first. That did not help. It wouldn't apply to a situation where ref00d is still working perfectly fine with 3.65-3.68 games already. Only this one game has an issue.

**Comment by Princess-of-Sleeping** [comment]
c1-6703-6 What is the request fw of the game returning an error?

**Comment by MessiahMozgus** [comment]
Game's final patch requests fw 3.65. 

I ended up not realizing I needed the repatch plugin installed as well, so I could use the compatibility patch for this game's v6.00 final patch. It still doesn't explain why ref00d can't bypass the FW requirement here like it does for all other 3.65-3.70 games I have installed, but at least I have it playable again.

**Comment by farley907** [comment]
If you used autoplugin to install this, try using vitashell, copy/paste the tai folder from ur0 to ux0 and see if that helps.

**Comment by Princess-of-Sleeping** [comment]
https://github.com/dots-tb/reF00D/issues/15
(Just because this problem has been fixed does not mean that the error will not occur)

**Comment by breacher18** [comment]
I had the same issue I just uninstalled ref00d through auto plugin rebooted then reinstalled rebooted then tried the game and it worked. Wasn’t expecting it to fix it but I’ll take a quick win :)

**Comment by CelesteBlue-dev** [comment]
@breacher18 Certainly because autoplugin uninstalled OLD ref00d and installed NEW ref00d
