### ISSUE TITLE
Is reF00D replaced by 0syscall6?

### ISSUE THREAD

**Issue by windsurfer1122** [dots-tb/reF00D#16]
The readme says:

> Please use: https://github.com/SKGleba/0syscall6/releases

Does it mean that 0syscall6 replaces reF00D? Or that 0syscall6 has to be used in conjunction with reF00D?

Please make readme more explicit. Thanks.

**Comment by RinMaru** [comment]
good question im curious aswell

**Comment by Masamune3210** [comment]
Replaces

**Comment by windsurfer1122** [comment]
Confirmed. Could start a 3.68+ game on PSTV with 3.65 Enso plus 0syscall6 (instead of reF00D) and DolcePolce (for PSTV).

**Comment by vanyasem** [comment]
I wonder if that is still the case with the release of [reF00D 1.1](https://github.com/dots-tb/reF00D/releases/tag/1.1)

Because all mentions of it being replaced with `0syscall6` were removed

**Comment by vanyasem** [comment]
Quote from [Reddit](https://www.reddit.com/r/vitahacks/comments/m4pvwz/comment/gqw1rnm):

[chaoskagami](https://www.reddit.com/user/chaoskagami/):

> 0syscall6 patches the code on the security processor to just ignore the version check since the keys are exactly the same on newer firmware and still work to decrypt newer games.
> 
> reF00D reimplements/emulates the calls for decryption, providing the keys via an alternative mechanism.
> 
> If Sony were to ever update the keys on the security processor in a firmware update, 0syscall6 would be unable to play games targeting that version or newer. reF00D, with a dump of newer keys, would still work. That said, given how dead the vita is at this point, I'm doubtful that will ever happen. 0syscall6 is therefore the better option since it's simpler, but reF00D is interesting from an implementation perspective.

**Comment by dyharlan** [comment]
###
