### ISSUE TITLE
Running higher FW system apps on FW3.65

### ISSUE THREAD

**Issue by 0lorak** [dots-tb/reF00D#17]
How do you take advantage of, for example, the FW 3.69 web browser with this plugin in FW 3.65 enso? 
I suppose that the first step is to somehow get the FW 3.69 web browser (a vpk or pkg?), to then install it. 
How do I get system apps -web browser- from FW 3.69?

**Comment by Princess-of-Sleeping** [comment]
This is not a issues with reF00D. So you can ask it in the best community.
