### ISSUE TITLE
Gun Gun Pixies VLJM-30231 physical cartridge launch error.

### ISSUE THREAD

**Issue by nightwishfan1** [dots-tb/reF00D#2]
I'm using the physical cartridge copy of Gun Gun Pixies which on the cart is labeled as VLJM-30231.  It seems it will not launch, and still gives the error c2-12828 like it would if installed on a system which doesn't meet the firmware requirements.  I commented the plugin as described in your instructions in my tai config.txt which is located at ux0:/tai with the plugin file itself along with my other plugins located in ur0:/tai which is also where the keys.bin was placed as well per your pages instructions.  It should also be noted I commented it, and I commented it as the file name reads where I'm pretty sure the zeros are just those....zeros.  And capitalized the F and D.  Your instructions however note the file can be un-capitalized, to which I'm unusre is of any relevance to this issue.  Anyway the issue persists, and I even for the heck of it decided to change the zeros to the letter O on the off chance that could've been a hang up, and even de-capitalized the F and D in my config.txt as your instructions note.  

Anyways to the specifics.  I'm not using NoNPDRM, or repatch plugins, and do not use autoplugin.  So those steps I'm sure could be avoided.  As for the other contents in ur0:/tai along with your plugin and keys.bin file are the following plugins:  RoActDat, DSMotion, and Oclock vita minimal.  I'm unsure of the issue, and any assistance would be appreciated.  Thanks.

**Comment by nightwishfan1** [comment]
Well I got advice from TheRadziu that apparently despite not being mentioned, that NoNpDRM is required to be installed I guess.  I went and retrieved that file, and edited my config.txt to clean it up just a smidge, and so that it loaded first before refood, and still got the same result.  No change.

**Comment by dots-tb** [comment]
Please tell me the location of the license within the cartridge. There should be a rif within a license/app folder. Thanks in advance.

Also what FW?

**Comment by nightwishfan1** [comment]
Well, ok, but to clarify now.  I've had correspondence with TheRadziu earlier, and I misinterpreted what he was saying.  Since I have the physical cartridge I do not need NoNpDRM it seems.  He said it was specifically for dumps to be able to use with your plugin.  Anyway if this game still requires this license, then where would I find it?  I got no idea how to look within the cartridge for the license you want, unless you mean it's specifically in one of the app folders for the game info, which I got no clue which one would have it.  Though I assume it can't be hard to find.

**Comment by nightwishfan1** [comment]
Well I got in from work not long ago, and I'm not sure what you're looking for.  Earlier I thought I needed NoNpDRM, but TheRadziu told me this wasn't the case as I have the physical cartridge so I have removed that plugin since the game does not require a fake license.  So again I'm really unsure of where to look, and I have no idea how to look within my cartridge.  Only thing I see on my pstv system for the game is a bit of files for the game is at ux0:appmeta/PCSG01013.  There's a sealed key file under sce_sys folder within that directory.  So the full directory looks like this ux0:appmeta/PCSG01013/sce_sys.  There's no extension on the file.  Just says sealed key.  If you're asking me to dump my own game then I got no clue how to do that, and really am not comfortable doing something I have no clue about.

I'm not sure if that's what you're after, cause again I discontinued use of NoNpDRM as it wasn't necessary.  As for my firmware version.  I'm on 3.65 enso.

**Comment by dots-tb** [comment]
W-why didn't you close the issue if it worked? You are correct, you do not need licenses as ref00d reads the licenses off the cartridge (gro0 and grw0), which is where the license folder for the specific game is, we just wanted to see if the path was different from anything else we have seen before. But I am going to close this issue. @nightwishfan1

**Comment by nightwishfan1** [comment]
@dots-tb I didn't close the issue cause even though I have the physical cartridge of the game, it still will not launch with your plugin.  The firmware Gun Gun Pixies requires is greater than 3.65.  Your plugin fails at letting me load the game.  I had no idea to even look at gro0 or grw0.  I'm not like you with this know how.  I can check those directories, and see if a key is present now that you made me aware of checking them.  You said in a app folder so I merely looked in the usual places that I know app folders exist, which are ux0 and ur0.  ux0 showed me some sort of sealed key within the folder I mentioned.

**Comment by dots-tb** [comment]
>Well I got in from work not long ago

Oh I read this wrong, I thought you said you got it to work not long ago. But it still stands under gro0 or grw0, there is a folder called license, then under that is app, then within that is a title id, within that is a license file, then write that location. What exactly is the error that pops up? @nightwishfan1 

Further note: I mean it does not need NoNpDrm licenses to use cartridge. And I am explaining the processes to you, please understand I can make mistakes.

**Comment by nightwishfan1** [comment]
Well the license is within the gro0:license/app/PCSG01013 directory.  The error I get would be the typical game launch failure error c2-12828-1 last I saw.  I can quickly confirm after this message and edit here as needed.  And I'm aware you can make mistakes.  I can make them as well.  You just rattled me a bit there with reading my message wrong.  

EDIT:  That error was the one.

**Comment by dots-tb** [comment]
Sorry man. Please tell me the name of the rif file within that folder please. Thanks.

**Comment by nightwishfan1** [comment]
Good thing I wrote it down then.  Rather long name to it, and it's below.  I'll make a quick re-read from the system to be sure it's correct.  Will reply with new file name if it isn't.

7b3a73700b540886d29362b8996f6aa1.rif

**Comment by dots-tb** [comment]
Also, by commenting the plugin do you mean adding it to the config.txt or commenting it out? And are the other plugins activated at the moment or disabled? Please post your config.txt. Thanks in advance.

**Comment by nightwishfan1** [comment]
Adding it to the config.txt.  As far as I know they are active on boot, though I don't know how any of them would be the culprit with screwing things up.

[config.txt](https://github.com/dots-tb/reF00D/files/2751805/config.txt)

**Comment by dots-tb** [comment]
Please try commenting out oclock minimal, reboot, and then try running the game.

**Comment by nightwishfan1** [comment]
I'll need a few moments.

**Comment by nightwishfan1** [comment]
That was the culprit.  Got the game to boot.  I don't know if you tested this plugin with your own overclock plugin, but I'd imagine you'd want to test that as well on games you yourself own.  This doesn't seem to play nice with such plugins.

**Comment by dots-tb** [comment]
I did not write oclock vita. I wrote LOLIcon, a kernel OC plugin. User plugins are prone to causing issues. This issue was not visible until you had used ref00d to access the game, which would normally not run. There is no issue with ref00d, so would you like me to close this?

**Comment by nightwishfan1** [comment]
You can close it man.  Thank you.  I only have 2 other games that are 3.65+ so there may be one other report once I get to either of those.
