### ISSUE TITLE
C1-6703-6 When Lauching PSM Dev

### ISSUE THREAD

**Issue by nolberto82** [dots-tb/reF00D#5]
I have nonpdrm before refood in config.txt and keys.bin in ur0:/tai/ and restarted the vita but I get the error everytime.

**Comment by dots-tb** [comment]
Do you know if ref00d is actually running? PSM dev is a known working application.

**Comment by nolberto82** [comment]
I don't know is there a way to know?

**Comment by nolberto82** [comment]
Does this plugin work on 3.60?

**Comment by dots-tb** [comment]
Yes. I tested PSM dev personally on my own 3.60 device. It worked for me. Try any other game that requires >3.60 and post your config.txt.

**Comment by nolberto82** [comment]
I tried 36 Fragments of Midnight same error,

[config.txt](https://github.com/dots-tb/reF00D/files/2757973/config.txt)

**Comment by dots-tb** [comment]
You have no config in ux0 to conflict with the ur0 one?

**Comment by nolberto82** [comment]
No config in ux0.

**Comment by dots-tb** [comment]
Have you tried installing with Autoplugin? or is that how you installed it? How was the PSM dev app installed?

**Comment by nolberto82** [comment]
I  installed the plugins with autoplugin and the app with pkgj.

**Comment by dots-tb** [comment]
Have you tried updating the PSM Dev app in the live area?

**Comment by nolberto82** [comment]
I updated from the live area still get the error.

**Comment by dots-tb** [comment]
Do you see licenses in ux0:license/app/<title id> ?

**Comment by nolberto82** [comment]
I see a .rif file for PSM Dev(PCSI00007).

**Comment by dots-tb** [comment]
What is the name of the rif? If you want, you can try this ver too.
[ref00d.zip](https://github.com/dots-tb/reF00D/files/2758034/ref00d.zip)

**Comment by nolberto82** [comment]
I tried your refood no good. RIF name is 6488b73b912a753a492e2714e9b38bc7.rif

**Comment by dots-tb** [comment]
Are you able to run any game from pkgj (ones that would normally run on your psv) using nonpdrm?

**Comment by nolberto82** [comment]
I tried a 3.55 game and it works.

**Comment by dots-tb** [comment]
Well I am not really sure then, sorry. I will leave the issue up, but I have gotten it to work on my 3.60 vita no problem. You are using enso, correct?

**Comment by nolberto82** [comment]
Yes I'm using Enso 3.60. Is there no other way making it work?

**Comment by dots-tb** [comment]
Try redownloading the ur0:tai/keys.bin and rebooting.

**Comment by nolberto82** [comment]
Try a new keys.bin and restarted but no good.

**Comment by dots-tb** [comment]
Well, the only thing I can think of is that ref00d is not starting up properly. Sorry... :(

**Comment by nolberto82** [comment]
Thank you for your help,

**Comment by LiEnby** [comment]
HMmmm very strange tbh

**Comment by TheRadziu** [comment]
~~have you tried running any 3.61+ game or update WITHOUT comp packs?~~ seems like you did
Do you use sd2vita or usb as ux0? 

I'm pretty sure you're having user error just like 99% of the people who reported same issue.

**Comment by nolberto82** [comment]
I have a sony memory card 32gb and using FTP.

**Comment by nolberto82** [comment]
I updated to 3.65 and refood works.

**Comment by CelesteBlue-dev** [comment]
cool now downgrade to 3.60.
