### ISSUE TITLE
Typo in the readme

### ISSUE THREAD

**Issue by simlevesque** [dots-tb/reF00D#6]
The readme on step one says:

> Add ref00d.skprx

The file is actually called "reF00D.skprx".

**Comment by simlevesque** [comment]
If the plugin loader is case insensitive sorry but I did not want to try it and maybe break something on my Vita but I believe that it is case sensitive.

**Comment by dots-tb** [comment]
Thanks I will beat up radziu later.

**Comment by TheRadziu** [comment]
Jokes on you, I didn't write this part XD
